# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PayAndExtendingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PayAndExtendingPage(object):
    def setupUi(self, PayAndExtendingPage):
        PayAndExtendingPage.setObjectName("PayAndExtendingPage")
        PayAndExtendingPage.resize(800, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(PayAndExtendingPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(50, 50, 50, 50)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 2)
        self.listView = QtWidgets.QListView(self.gridLayoutWidget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 2, 0, 1, 2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 1, 2, 1)

        self.retranslateUi(PayAndExtendingPage)
        QtCore.QMetaObject.connectSlotsByName(PayAndExtendingPage)

    def retranslateUi(self, PayAndExtendingPage):
        _translate = QtCore.QCoreApplication.translate
        PayAndExtendingPage.setWindowTitle(_translate("PayAndExtendingPage", "Form"))
        self.pushButton_2.setText(_translate("PayAndExtendingPage", "PushButton"))
        self.pushButton.setText(_translate("PayAndExtendingPage", "PushButton"))
        self.checkBox.setText(_translate("PayAndExtendingPage", "CheckBox"))
        self.checkBox_2.setText(_translate("PayAndExtendingPage", "CheckBox"))
        self.radioButton.setText(_translate("PayAndExtendingPage", "RadioButton"))
