# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperOptionPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuperOptionsPage(object):
    def setupUi(self, SuperOptionsPage):
        SuperOptionsPage.setObjectName("SuperOptionsPage")
        SuperOptionsPage.resize(800, 600)

        self.retranslateUi(SuperOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(SuperOptionsPage)

    def retranslateUi(self, SuperOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        SuperOptionsPage.setWindowTitle(_translate("SuperOptionsPage", "Form"))
