# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RentingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RentingPage(object):
    def setupUi(self, RentingPage):
        RentingPage.setObjectName("RentingPage")
        RentingPage.resize(800, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(RentingPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 801, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(75, 75, 75, 75)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.QueryButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.QueryButton.setObjectName("QueryButton")
        self.gridLayout.addWidget(self.QueryButton, 4, 0, 1, 2)
        self.RentButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.RentButton.setObjectName("RentButton")
        self.gridLayout.addWidget(self.RentButton, 5, 0, 1, 2)
        self.BookNameLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.BookNameLine.setObjectName("BookNameLine")
        self.gridLayout.addWidget(self.BookNameLine, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.BookTypeCombo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.BookTypeCombo.setObjectName("BookTypeCombo")
        self.gridLayout.addWidget(self.BookTypeCombo, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.GoBackButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.GoBackButton.setObjectName("GoBackButton")
        self.gridLayout.addWidget(self.GoBackButton, 6, 0, 1, 2)
        self.RentedBookView = QtWidgets.QTableView(self.gridLayoutWidget)
        self.RentedBookView.setObjectName("RentedBookView")
        self.gridLayout.addWidget(self.RentedBookView, 3, 1, 1, 1)
        self.BooksView = QtWidgets.QTableView(self.gridLayoutWidget)
        self.BooksView.setObjectName("BooksView")
        self.gridLayout.addWidget(self.BooksView, 3, 0, 1, 1)

        self.retranslateUi(RentingPage)
        QtCore.QMetaObject.connectSlotsByName(RentingPage)

    def retranslateUi(self, RentingPage):
        _translate = QtCore.QCoreApplication.translate
        RentingPage.setWindowTitle(_translate("RentingPage", "Form"))
        self.label_2.setText(_translate("RentingPage", "Your books"))
        self.label_4.setText(_translate("RentingPage", "BookName"))
        self.QueryButton.setText(_translate("RentingPage", "Query"))
        self.RentButton.setText(_translate("RentingPage", "Rent!"))
        self.label.setText(_translate("RentingPage", "Able Books"))
        self.label_3.setText(_translate("RentingPage", "Book Type"))
        self.GoBackButton.setText(_translate("RentingPage", "Back"))
