# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReturnPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReturnPage(object):
    def setupUi(self, ReturnPage):
        ReturnPage.setObjectName("ReturnPage")
        ReturnPage.resize(400, 300)

        self.retranslateUi(ReturnPage)
        QtCore.QMetaObject.connectSlotsByName(ReturnPage)

    def retranslateUi(self, ReturnPage):
        _translate = QtCore.QCoreApplication.translate
        ReturnPage.setWindowTitle(_translate("ReturnPage", "Form"))
