# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReturnPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReturnPage(object):
    def setupUi(self, ReturnPage):
        ReturnPage.setObjectName("ReturnPage")
        ReturnPage.resize(800, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(ReturnPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(50, 50, 50, 50)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 4)
        self.UnreturnedList = QtWidgets.QTableView(self.gridLayoutWidget)
        self.UnreturnedList.setObjectName("UnreturnedList")
        self.gridLayout.addWidget(self.UnreturnedList, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 4)
        self.ReturnButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ReturnButton.setObjectName("ReturnButton")
        self.gridLayout.addWidget(self.ReturnButton, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.GoBackButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.GoBackButton.setObjectName("GoBackButton")
        self.gridLayout.addWidget(self.GoBackButton, 3, 3, 1, 1)
        self.RefreshButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.RefreshButton.setObjectName("RefreshButton")
        self.gridLayout.addWidget(self.RefreshButton, 3, 1, 1, 1)

        self.retranslateUi(ReturnPage)
        QtCore.QMetaObject.connectSlotsByName(ReturnPage)

    def retranslateUi(self, ReturnPage):
        _translate = QtCore.QCoreApplication.translate
        ReturnPage.setWindowTitle(_translate("ReturnPage", "Form"))
        self.label_2.setText(_translate("ReturnPage", "Here is your Renting History, select the one you want to return!"))
        self.ReturnButton.setText(_translate("ReturnPage", "Return!"))
        self.label.setText(_translate("ReturnPage", "TextLabel"))
        self.GoBackButton.setText(_translate("ReturnPage", "Go Back"))
        self.RefreshButton.setText(_translate("ReturnPage", "Refresh"))
