# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuperPage(object):
    def setupUi(self, SuperPage):
        SuperPage.setObjectName("SuperPage")
        SuperPage.resize(800, 600)

        self.retranslateUi(SuperPage)
        QtCore.QMetaObject.connectSlotsByName(SuperPage)

    def retranslateUi(self, SuperPage):
        _translate = QtCore.QCoreApplication.translate
        SuperPage.setWindowTitle(_translate("SuperPage", "Form"))
