# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PayMoneyPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PayMoneyPage(object):
    def setupUi(self, PayMoneyPage):
        PayMoneyPage.setObjectName("PayMoneyPage")
        PayMoneyPage.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(PayMoneyPage)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.PriceView = QtWidgets.QTableView(self.formLayoutWidget)
        self.PriceView.setObjectName("PriceView")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.PriceView)
        self.InfoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.InfoLabel.setObjectName("InfoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.InfoLabel)
        self.NopeButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.NopeButton.setObjectName("NopeButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.NopeButton)
        self.PayButon = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PayButon.setObjectName("PayButon")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PayButon)

        self.retranslateUi(PayMoneyPage)
        QtCore.QMetaObject.connectSlotsByName(PayMoneyPage)

    def retranslateUi(self, PayMoneyPage):
        _translate = QtCore.QCoreApplication.translate
        PayMoneyPage.setWindowTitle(_translate("PayMoneyPage", "Dialog"))
        self.InfoLabel.setText(_translate("PayMoneyPage", "TextLabel"))
        self.NopeButton.setText(_translate("PayMoneyPage", "Nope"))
        self.PayButon.setText(_translate("PayMoneyPage", "Pay All Money"))
