# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserEditPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserEditPage(object):
    def setupUi(self, UserEditPage):
        UserEditPage.setObjectName("UserEditPage")
        UserEditPage.resize(800, 600)

        self.retranslateUi(UserEditPage)
        QtCore.QMetaObject.connectSlotsByName(UserEditPage)

    def retranslateUi(self, UserEditPage):
        _translate = QtCore.QCoreApplication.translate
        UserEditPage.setWindowTitle(_translate("UserEditPage", "Form"))
